server:
  port : 9999
zuul:
  routes:
    offer:
      path: /offer/**
      url: http://3.109.201.33:1001/api/v1
    shoe:
      path: /shoe/**
      url: http://3.109.201.33:1002/api/v1
    wishlist:
      path: /wishlist/**
      url: http://3.109.201.33:1003
    cart:
      path: /cart/**
      url: http://3.109.201.33:1004/api/v1
